version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=weekly_report
      - MYSQL_ROOT_PASSWORD=root
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    #  - ./mysql/data:/var/lib/mysql    # mysql 数据存储目录

  nginx:
    depends_on:
      - mysql
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: always
    privileged: true
    ports:
      - 8980:8980
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web/dist:/usr/local/web

  golang:
    depends_on:
      - mysql
    image: golang:1.16.10-alpine
    container_name: weekly_report
    working_dir: /usr/local/weekly_report
    command: go run /usr/local/weekly_report/main.go
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true
    restart: always
    ports:
      - 8981:8981
    volumes:
      - ../server/:/usr/local/weekly_report
      - ./web/:/usr/local/web

    # alpine 更新时间
    # echo 'http://mirrors.ustc.edu.cn/alpine/v3.5/main' > /etc/apk/repositories
    # echo 'http://mirrors.ustc.edu.cn/alpine/v3.5/community' >>/etc/apk/repositories
    # 时间同步: RUN apk add tzdata ; cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && apk del tzdata

