version: '3.0'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_weekly
    restart: always
    environment:
      MYSQL_DATABASE: weekly_report
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d

  nginx:
    depends_on:
      - mysql
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: always
    ports:
    - 8980:8980
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./build/:/usr/local/build/

  golang:
    depends_on:
      - mysql
    image: golang:1.16.10-alpine
    container_name: weekly_report
    working_dir: /usr/local/weekly_report
    command: go run /usr/local/weekly_report/main.go
    restart: always
    ports:
    - 8981:8888
    volumes:
    - ../server/:/usr/local/weekly_report

